
language: java

jdk:
  - openjdk8
  - openjdk11
arch:
  - amd64
  - ppc64le
addons:
  apt:
    packages:
      - graphviz

script: "mvn --show-version --errors --batch-mode -Prun-its clean verify"

cache:
    directories:
    - $HOME/.m2

branches:
    except:
        - gh-pages

notifications:
    email:
        - lennart.jorelid@gmail.com
