/**
 * <p>The jaxb2-maven-plugin wraps and adapts the <a href="https://jaxb.java.net/">JAXB reference implementation</a>
 * to be useful within the Maven build process.</p>
 * <p>The schemageneneration package (including subpackages) contains Mojos for generating XSD files from
 * annotated Java classes. It also contains subpackages for post-processing the results of the schemagen tool,
 * to create XSDs with better usability than the XSDs generated by default.</p>
 *
 * @author <a href="mailto:lj@jguru.se">Lennart J&ouml;relid</a>
 * @see <a href="https://jaxb.java.net/">The JAXB Reference Implementation</a>
 */
package org.codehaus.mojo.jaxb2.schemageneration;
